/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CriacaoDeSitesRouteImport } from './routes/criacao-de-sites'
import { Route as GoogleMeuNegocioRouteImport } from './routes/google-meu-negocio'
import { Route as LojaVirtualRouteImport } from './routes/loja-virtual'
import { Route as TrafegoPagoRouteImport } from './routes/trafego-pago'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriacaoDeSitesRoute = CriacaoDeSitesRouteImport.update({
  id: '/criacao-de-sites',
  path: '/criacao-de-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const GoogleMeuNegocioRoute = GoogleMeuNegocioRouteImport.update({
  id: '/google-meu-negocio',
  path: '/google-meu-negocio',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaVirtualRoute = LojaVirtualRouteImport.update({
  id: '/loja-virtual',
  path: '/loja-virtual',
  getParentRoute: () => rootRouteImport,
} as any)
const TrafegoPagoRoute = TrafegoPagoRouteImport.update({
  id: '/trafego-pago',
  path: '/trafego-pago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/loja-virtual': typeof LojaVirtualRoute
  '/trafego-pago': typeof TrafegoPagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/loja-virtual': typeof LojaVirtualRoute
  '/trafego-pago': typeof TrafegoPagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criacao-de-sites': typeof CriacaoDeSitesRoute
  '/google-meu-negocio': typeof GoogleMeuNegocioRoute
  '/loja-virtual': typeof LojaVirtualRoute
  '/trafego-pago': typeof TrafegoPagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criacao-de-sites'
    | '/google-meu-negocio'
    | '/loja-virtual'
    | '/trafego-pago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criacao-de-sites'
    | '/google-meu-negocio'
    | '/loja-virtual'
    | '/trafego-pago'
  id:
    | '__root__'
    | '/'
    | '/criacao-de-sites'
    | '/google-meu-negocio'
    | '/loja-virtual'
    | '/trafego-pago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriacaoDeSitesRoute: typeof CriacaoDeSitesRoute
  GoogleMeuNegocioRoute: typeof GoogleMeuNegocioRoute
  LojaVirtualRoute: typeof LojaVirtualRoute
  TrafegoPagoRoute: typeof TrafegoPagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criacao-de-sites': {
      id: '/criacao-de-sites'
      path: '/criacao-de-sites'
      fullPath: '/criacao-de-sites'
      preLoaderRoute: typeof CriacaoDeSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/google-meu-negocio': {
      id: '/google-meu-negocio'
      path: '/google-meu-negocio'
      fullPath: '/google-meu-negocio'
      preLoaderRoute: typeof GoogleMeuNegocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja-virtual': {
      id: '/loja-virtual'
      path: '/loja-virtual'
      fullPath: '/loja-virtual'
      preLoaderRoute: typeof LojaVirtualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trafego-pago': {
      id: '/trafego-pago'
      path: '/trafego-pago'
      fullPath: '/trafego-pago'
      preLoaderRoute: typeof TrafegoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriacaoDeSitesRoute: CriacaoDeSitesRoute,
  GoogleMeuNegocioRoute: GoogleMeuNegocioRoute,
  LojaVirtualRoute: LojaVirtualRoute,
  TrafegoPagoRoute: TrafegoPagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
